/**
 * Created by maj on 4/3/16.
 */

/*create an array for the 4 suits of cards*/
suits = ["diamonds", "clubs", "hearts", "spades"];
ranks = "A23456789TJQK";
deck = new Array(ranks.length * suits.length);

/**
 * Card - declare properties of Card deck
 * @type constructor
 * @params r, s
 *
 */
function Card(r,s) {
    this.rank = r;
    this.suit = s;
    this.cardName = r + " of " + s;
}

/**
 * theDeck - declare properties of Card deck
 * @type constructor
 * @params r, s
 *
 */

function theDeck() {
    for (var i = 0; i < suits.length; i++) {
        for (var j = 0; j < ranks.length; j++) {
            deck[j + i * ranks.length] = new Card(ranks[j], suits[i]);
        }
        return deck;
    }
}


/**
 * shuffler - shuffles the deck of cards generated by theDeck() then utilizes the Fisher Yates algorithm to shuffle.
 * @
 * @params r, s
 *
 */

function shuffler(array) {
    var m = array.length,
        t, i;

    // While there remain elements to shuffle…
    while (m) {

        // Pick a remaining element…
        i = Math.floor(Math.random() * m--);

        // And swap it with the current element.
        t = array[m];
        array[m] = array[i];
        array[i] = t;
    }

    return array;
}

/**
 * shuffler - shuffles the deck of cards generated by theDeck() then utilizes the Fisher Yates algorithm to shuffle.
 * @
 * @params r, s
 *
 */
function showShuffled() {
    myDeck = getDeck()
    shuffle(myDeck);
    document.getElementById("second").innerHTML = "";
    showElmntProperty("myDeck", "cardName", "second");
    document.getElementById("third").innerHTML = "";
}

document.getElementById("sh").addEventListener("click", showShuffled);